### ISSUE TITLE
Wong.R: cannot find R package called en.lab

### ISSUE THREAD

**Issue by vitcat** [ebecht/DR_benchmark#2]
Hi, I'm new to R and thank you for contributions! I'd like to rerun the codes but need some help. 
In Wong.R in Wong file, we need to use library en.lab in line 2. but I cannot find it on the website. Is it a typo or which is the package I need to download?
Thank you in advance!

**Comment by ebecht** [comment]
Hi and thank you for looking at our work,
I believe that line is not needed.  Before we made the code public, we rewrote the parts that used functions from `en.lab` in base R. This seems like it's a leftover.
As you noticed, `toColors_continuous` is in `utils.R`

Please let me know if you happen to run into missing function definitions after commenting out `library(en.lab)`
